//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WcfService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MB.WcfService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO BF_MODULE_COMMENT (ID ,APPLICATION_IDENTITY ,MODULE_IDENTITY ,COMMENT_TYPE,COMMENT_CONTENT ,USER_ID ,CREATE_DATE,LAST_MODIFIED_DATE ) VALUES(:ID,:APPLICATION_IDENTITY ,:MODULE_IDENTITY,:COMMENT_TYPE ,:COMMENT_CONTENT ,:USER_ID ,SYSTIMESTAMP ,SYSTIMESTAMP  ).
        /// </summary>
        internal static string BfModuleComment_Sql_AddObject {
            get {
                return ResourceManager.GetString("BfModuleComment_Sql_AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM BF_MODULE_COMMENT WHERE APPLICATION_IDENTITY = :APPLICATION_IDENTITY AND MODULE_IDENTITY=:MODULE_IDENTITY.
        /// </summary>
        internal static string BfModuleComment_Sql_ClearObject {
            get {
                return ResourceManager.GetString("BfModuleComment_Sql_ClearObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM BF_MODULE_COMMENT WHERE ID = :ID.
        /// </summary>
        internal static string BfModuleComment_Sql_DeleteObject {
            get {
                return ResourceManager.GetString("BfModuleComment_Sql_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID ,APPLICATION_IDENTITY ,MODULE_IDENTITY,COMMENT_TYPE ,COMMENT_CONTENT ,USER_ID ,CREATE_DATE ,LAST_MODIFIED_DATE FROM BF_MODULE_COMMENT WHERE {0}.
        /// </summary>
        internal static string BfModuleComment_Sql_SelectObject {
            get {
                return ResourceManager.GetString("BfModuleComment_Sql_SelectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CHART_LAYOUT_ITEM(ID,LT_ID,CT_ID,NAME,TEXT,FORM_TEXT,ITEM_TYPE) VALUES(:ID ,:LT_ID ,:CT_ID ,:NAME,:TEXT,:FORM_TEXT,:ITEM_TYPE).
        /// </summary>
        internal static string ChartLayoutItem_Sql_AddObject {
            get {
                return ResourceManager.GetString("ChartLayoutItem_Sql_AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM CHART_LAYOUT_ITEM WHERE LT_ID = :ID.
        /// </summary>
        internal static string ChartLayoutItem_Sql_DeleteObject {
            get {
                return ResourceManager.GetString("ChartLayoutItem_Sql_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID,LT_ID,CT_ID,NAME,TEXT,FORM_TEXT,ITEM_TYPE FROM CHART_LAYOUT_ITEM WHERE LT_ID = :ID.
        /// </summary>
        internal static string ChartLayoutItem_Sql_SelectObject {
            get {
                return ResourceManager.GetString("ChartLayoutItem_Sql_SelectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM CHART_LAYOUT_TEMPLATE WHERE ID = :ID.
        /// </summary>
        internal static string ChartLayoutTempalte_Sql_DeleteObject {
            get {
                return ResourceManager.GetString("ChartLayoutTempalte_Sql_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CHART_LAYOUT_TEMPLATE (ID,NAME,TEMPLATE_TYPE,TEMPLATE_FILE,CREATE_USER,CREATE_DATE) VALUES(:ID,:NAME,:TEMPLATE_TYPE,:TEMPLATE_FILE,:CREATE_USER,SYSTIMESTAMP).
        /// </summary>
        internal static string ChartLayoutTemplate_Sql_AddObject {
            get {
                return ResourceManager.GetString("ChartLayoutTemplate_Sql_AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID,NAME,TEMPLATE_TYPE,TEMPLATE_FILE,CREATE_USER,CREATE_DATE FROM CHART_LAYOUT_TEMPLATE WHERE {0}.
        /// </summary>
        internal static string ChartLayoutTemplate_Sql_SelectObject {
            get {
                return ResourceManager.GetString("ChartLayoutTemplate_Sql_SelectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CHART_TEMPLATE (ID ,NAME ,RULE_PATH ,GRID_NAME,FILTER_STRING ,TEMPLATE_FILE ,TEMPLATE_TYPE ,CREATE_USER ,CREATE_DATE ) VALUES( :ID ,:NAME ,:RULE_PATH ,:GRID_NAME,:FILTER_STRING ,:TEMPLATE_FILE  ,:TEMPLATE_TYPE ,:CREATE_USER ,SYSTIMESTAMP ).
        /// </summary>
        internal static string ChartTemplate_Sql_AddObject {
            get {
                return ResourceManager.GetString("ChartTemplate_Sql_AddObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM CHART_TEMPLATE WHERE ID = :ID.
        /// </summary>
        internal static string ChartTemplate_Sql_DeleteObject {
            get {
                return ResourceManager.GetString("ChartTemplate_Sql_DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID,NAME,RULE_PATH,GRID_NAME,FILTER_STRING,TEMPLATE_FILE,TEMPLATE_TYPE,CREATE_USER,CREATE_DATE FROM CHART_TEMPLATE WHERE {0}.
        /// </summary>
        internal static string ChartTemplate_Sql_SelectObject {
            get {
                return ResourceManager.GetString("ChartTemplate_Sql_SelectObject", resourceCulture);
            }
        }
    }
}
