//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.SOA.Web.BtsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest", ConfigurationName="BtsService.BtsMAServer")]
    public interface BtsMAServer {
        
        // CODEGEN: 操作 MA_PKT 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="MA_PKT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MB.SOA.Web.BtsService.MA_PKTResponse MA_PKT(MB.SOA.Web.BtsService.MA_PKTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest")]
    public partial class OrdersOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrdersOrderHeader headerField;
        
        private OrdersOrderDetails[] detailsField;
        
        private OrdersOrderBoxHeaders[] boxHeadersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrdersOrderHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public OrdersOrderDetails[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoxHeaders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrdersOrderBoxHeaders[] BoxHeaders {
            get {
                return this.boxHeadersField;
            }
            set {
                this.boxHeadersField = value;
                this.RaisePropertyChanged("BoxHeaders");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest")]
    public partial class OrdersOrderHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wif_NumField;
        
        private string ship_ViaField;
        
        private string ship_DateTimeField;
        
        private string user_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Wif_Num {
            get {
                return this.wif_NumField;
            }
            set {
                this.wif_NumField = value;
                this.RaisePropertyChanged("Wif_Num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ship_Via {
            get {
                return this.ship_ViaField;
            }
            set {
                this.ship_ViaField = value;
                this.RaisePropertyChanged("Ship_Via");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ship_DateTime {
            get {
                return this.ship_DateTimeField;
            }
            set {
                this.ship_DateTimeField = value;
                this.RaisePropertyChanged("Ship_DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
                this.RaisePropertyChanged("User_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest")]
    public partial class OrdersOrderDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prod_IDField;
        
        private string allow_QtyField;
        
        private string delivered_QtyField;
        
        private string cancel_QtyField;
        
        private string order_QtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Prod_ID {
            get {
                return this.prod_IDField;
            }
            set {
                this.prod_IDField = value;
                this.RaisePropertyChanged("Prod_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Allow_Qty {
            get {
                return this.allow_QtyField;
            }
            set {
                this.allow_QtyField = value;
                this.RaisePropertyChanged("Allow_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Delivered_Qty {
            get {
                return this.delivered_QtyField;
            }
            set {
                this.delivered_QtyField = value;
                this.RaisePropertyChanged("Delivered_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Cancel_Qty {
            get {
                return this.cancel_QtyField;
            }
            set {
                this.cancel_QtyField = value;
                this.RaisePropertyChanged("Cancel_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Order_Qty {
            get {
                return this.order_QtyField;
            }
            set {
                this.order_QtyField = value;
                this.RaisePropertyChanged("Order_Qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest")]
    public partial class OrdersOrderBoxHeaders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string box_NumField;
        
        private string box_TypeField;
        
        private string box_SizeField;
        
        private string box_VolField;
        
        private string box_WTField;
        
        private string total_QtyField;
        
        private string start_TimeField;
        
        private string close_TimeField;
        
        private OrdersOrderBoxHeadersBoxDetails[] boxDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Box_Num {
            get {
                return this.box_NumField;
            }
            set {
                this.box_NumField = value;
                this.RaisePropertyChanged("Box_Num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Box_Type {
            get {
                return this.box_TypeField;
            }
            set {
                this.box_TypeField = value;
                this.RaisePropertyChanged("Box_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Box_Size {
            get {
                return this.box_SizeField;
            }
            set {
                this.box_SizeField = value;
                this.RaisePropertyChanged("Box_Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Box_Vol {
            get {
                return this.box_VolField;
            }
            set {
                this.box_VolField = value;
                this.RaisePropertyChanged("Box_Vol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Box_WT {
            get {
                return this.box_WTField;
            }
            set {
                this.box_WTField = value;
                this.RaisePropertyChanged("Box_WT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Total_Qty {
            get {
                return this.total_QtyField;
            }
            set {
                this.total_QtyField = value;
                this.RaisePropertyChanged("Total_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Start_Time {
            get {
                return this.start_TimeField;
            }
            set {
                this.start_TimeField = value;
                this.RaisePropertyChanged("Start_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Close_Time {
            get {
                return this.close_TimeField;
            }
            set {
                this.close_TimeField = value;
                this.RaisePropertyChanged("Close_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoxDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public OrdersOrderBoxHeadersBoxDetails[] BoxDetails {
            get {
                return this.boxDetailsField;
            }
            set {
                this.boxDetailsField = value;
                this.RaisePropertyChanged("BoxDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest")]
    public partial class OrdersOrderBoxHeadersBoxDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string prod_IDField;
        
        private string act_QtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Prod_ID {
            get {
                return this.prod_IDField;
            }
            set {
                this.prod_IDField = value;
                this.RaisePropertyChanged("Prod_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Act_Qty {
            get {
                return this.act_QtyField;
            }
            set {
                this.act_QtyField = value;
                this.RaisePropertyChanged("Act_Qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MA_PKTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://MBEAI.WMS.OutPKT.WMS_PKT_VariantRequest", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MB.SOA.Web.BtsService.OrdersOrder[] Orders;
        
        public MA_PKTRequest() {
        }
        
        public MA_PKTRequest(MB.SOA.Web.BtsService.OrdersOrder[] Orders) {
            this.Orders = Orders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MA_PKTResponse {
        
        public MA_PKTResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BtsMAServerChannel : MB.SOA.Web.BtsService.BtsMAServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BtsMAServerClient : System.ServiceModel.ClientBase<MB.SOA.Web.BtsService.BtsMAServer>, MB.SOA.Web.BtsService.BtsMAServer {
        
        public BtsMAServerClient() {
        }
        
        public BtsMAServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BtsMAServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BtsMAServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BtsMAServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MB.SOA.Web.BtsService.MA_PKTResponse MB.SOA.Web.BtsService.BtsMAServer.MA_PKT(MB.SOA.Web.BtsService.MA_PKTRequest request) {
            return base.Channel.MA_PKT(request);
        }
        
        public void MA_PKT(MB.SOA.Web.BtsService.OrdersOrder[] Orders) {
            MB.SOA.Web.BtsService.MA_PKTRequest inValue = new MB.SOA.Web.BtsService.MA_PKTRequest();
            inValue.Orders = Orders;
            MB.SOA.Web.BtsService.MA_PKTResponse retVal = ((MB.SOA.Web.BtsService.BtsMAServer)(this)).MA_PKT(inValue);
        }
    }
}
