//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WinClientDefault.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MB.WinClientDefault.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般评语.
        /// </summary>
        internal static string BfModlueComment_COMMENT_TYPE1 {
            get {
                return ResourceManager.GetString("BfModlueComment_COMMENT_TYPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统 BUG.
        /// </summary>
        internal static string BfModlueComment_COMMENT_TYPE2 {
            get {
                return ResourceManager.GetString("BfModlueComment_COMMENT_TYPE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能缺陷.
        /// </summary>
        internal static string BfModlueComment_COMMENT_TYPE3 {
            get {
                return ResourceManager.GetString("BfModlueComment_COMMENT_TYPE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需求建议.
        /// </summary>
        internal static string BfModlueComment_COMMENT_TYPE4 {
            get {
                return ResourceManager.GetString("BfModlueComment_COMMENT_TYPE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求帮助.
        /// </summary>
        internal static string BfModlueComment_COMMENT_TYPE5 {
            get {
                return ResourceManager.GetString("BfModlueComment_COMMENT_TYPE5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者 {0}   {1}    发表于 {2}  
        ///.
        /// </summary>
        internal static string BfModuleComment_COMMENT_TITLE {
            get {
                return ResourceManager.GetString("BfModuleComment_COMMENT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前编辑的评语长度超过 {0} 字节,请重新编辑.
        /// </summary>
        internal static string BfModuleComment_MAX_COMMENT_LENGTH {
            get {
                return ResourceManager.GetString("BfModuleComment.MAX_COMMENT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入模块评语.
        /// </summary>
        internal static string BfModuleComment_MIN_COMMENT_CHECK {
            get {
                return ResourceManager.GetString("BfModuleComment_MIN_COMMENT_CHECK", resourceCulture);
            }
        }
    }
}
