//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/MB.EAI.SOA.BANGGO.Entities")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeasonCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.SkuVo[] SkuVosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThemeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandCodeField, value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsName {
            get {
                return this.GoodsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsNameField, value) != true)) {
                    this.GoodsNameField = value;
                    this.RaisePropertyChanged("GoodsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsSn {
            get {
                return this.GoodsSnField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsSnField, value) != true)) {
                    this.GoodsSnField = value;
                    this.RaisePropertyChanged("GoodsSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsWeight {
            get {
                return this.GoodsWeightField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsWeightField, value) != true)) {
                    this.GoodsWeightField = value;
                    this.RaisePropertyChanged("GoodsWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketPrice {
            get {
                return this.MarketPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketPriceField, value) != true)) {
                    this.MarketPriceField = value;
                    this.RaisePropertyChanged("MarketPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpType {
            get {
                return this.OpTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpTypeField, value) != true)) {
                    this.OpTypeField = value;
                    this.RaisePropertyChanged("OpType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalePoint {
            get {
                return this.SalePointField;
            }
            set {
                if ((object.ReferenceEquals(this.SalePointField, value) != true)) {
                    this.SalePointField = value;
                    this.RaisePropertyChanged("SalePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeasonCode {
            get {
                return this.SeasonCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonCodeField, value) != true)) {
                    this.SeasonCodeField = value;
                    this.RaisePropertyChanged("SeasonCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeriesCode {
            get {
                return this.SeriesCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesCodeField, value) != true)) {
                    this.SeriesCodeField = value;
                    this.RaisePropertyChanged("SeriesCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.SkuVo[] SkuVos {
            get {
                return this.SkuVosField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuVosField, value) != true)) {
                    this.SkuVosField = value;
                    this.RaisePropertyChanged("SkuVos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThemeCode {
            get {
                return this.ThemeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThemeCodeField, value) != true)) {
                    this.ThemeCodeField = value;
                    this.RaisePropertyChanged("ThemeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkuVo", Namespace="http://schemas.datacontract.org/2004/07/MB.EAI.SOA.BANGGO.Entities")]
    [System.SerializableAttribute()]
    public partial class SkuVo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustumCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorCode {
            get {
                return this.ColorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorCodeField, value) != true)) {
                    this.ColorCodeField = value;
                    this.RaisePropertyChanged("ColorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName {
            get {
                return this.ColorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorNameField, value) != true)) {
                    this.ColorNameField = value;
                    this.RaisePropertyChanged("ColorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustumCode {
            get {
                return this.CustumCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustumCodeField, value) != true)) {
                    this.CustumCodeField = value;
                    this.RaisePropertyChanged("CustumCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsSn {
            get {
                return this.GoodsSnField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsSnField, value) != true)) {
                    this.GoodsSnField = value;
                    this.RaisePropertyChanged("GoodsSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpType {
            get {
                return this.OpTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpTypeField, value) != true)) {
                    this.OpTypeField = value;
                    this.RaisePropertyChanged("OpType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SizeCode {
            get {
                return this.SizeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeCodeField, value) != true)) {
                    this.SizeCodeField = value;
                    this.RaisePropertyChanged("SizeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SizeName {
            get {
                return this.SizeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeNameField, value) != true)) {
                    this.SizeNameField = value;
                    this.RaisePropertyChanged("SizeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMSG", Namespace="http://schemas.datacontract.org/2004/07/MB.EAI.SOA.BANGGO.Entities")]
    [System.SerializableAttribute()]
    public partial class ReturnMSG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isok {
            get {
                return this.isokField;
            }
            set {
                if ((this.isokField.Equals(value) != true)) {
                    this.isokField = value;
                    this.RaisePropertyChanged("isok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MB.EAI.SOA.BANGGO/IBanggoServiceProxy", ConfigurationName="ServiceReference1.IBanggoServiceProxy")]
    public interface IBanggoServiceProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MB.EAI.SOA.BANGGO/IBanggoServiceProxy/IBanggoServiceProxy/SaveProduct", ReplyAction="http://MB.EAI.SOA.BANGGO/IBanggoServiceProxy/IBanggoServiceProxy/SaveProductRespo" +
            "nse")]
        ConsoleApplication1.ServiceReference1.ReturnMSG SaveProduct(ConsoleApplication1.ServiceReference1.ProductInfo prod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBanggoServiceProxyChannel : ConsoleApplication1.ServiceReference1.IBanggoServiceProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanggoServiceProxyClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IBanggoServiceProxy>, ConsoleApplication1.ServiceReference1.IBanggoServiceProxy {
        
        public BanggoServiceProxyClient() {
        }
        
        public BanggoServiceProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanggoServiceProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanggoServiceProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanggoServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.ReturnMSG SaveProduct(ConsoleApplication1.ServiceReference1.ProductInfo prod) {
            return base.Channel.SaveProduct(prod);
        }
    }
}
